# Generated by Django 5.1.6 on 2025-02-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
